server:
  port: 8083
spring:
  application:
    name: tenet-goods

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tenet-goods?useUnicode=true&serverTimezone=GMT&useSSL=false&characterEncoding=utf8
    username: root
    password: root
  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: df36a156-07e7-4e8e-b423-ef5fd7987fc8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl


dubbo:
  application:
    name: tenet-goods
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://127.0.0.1:8848
    check: true
    group: dubbo-dev
    simplified: true
    username: nacos
    password: nacos
    parameters:
      namespace: df36a156-07e7-4e8e-b423-ef5fd7987fc8
  scan:
    base-packages: com.tenet.goods.api.impl

logging:
  level: {com: "debug"}