server:
  port: 8084
spring:
  application:
    name: tenet-search
  data:
    elasticsearch:
      client:
        reactive:
          endpoints: 127.0.0.1:9200

  cloud:
    nacos:
      # Nacos 服务发现与注册配置
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        namespace: df36a156-07e7-4e8e-b423-ef5fd7987fc8


dubbo:
  application:
    name: tenet-search
  protocol:
    name: dubbo
    port: 20882
  registry:
    address: nacos://127.0.0.1:8848
    check: false
    group: dubbo-dev
    simplified: false
    username: nacos
    password: nacos
    zone: dubbo
    parameters:
      namespace: df36a156-07e7-4e8e-b423-ef5fd7987fc8
  provider:
    group: tenet
    version: 1.0.0
  consumer:
    group: tenet
    version: 1.0.0
    check: false